### ISSUE TITLE
jira: addPreProcessor is deprecated, please use the new markdown it APIs

### ISSUE THREAD

**Issue by trobiyo** [Axel-Naumann/discourse-jira#1]
Hi,

When using this plugin, we get the following message from console, resulting in no link to the JIRA project as it states in the plugin documentation.

```
jira: addPreProcessor is deprecated, please use the new markdown it APIs
```

**Comment by Axel-Naumann** [comment]
Sorry, I'm not going to fix this: we moved from JIRA to Github Issues, I cannot maintain this anymore :-(
